---
- name: "End-to-end Aegir 3 build from git source."
  hosts: all

  # Supply values for mysql_root_password and aegir_frontend_url.

  vars:
    ### Dependency roles
    nginx_manage_config: False
    nginx_remove_default_vhost: True
    php_cli_memory_limit: "2048M"
    php_enable_php_fpm: True
    php_enable_webserver: False
    php_set_cli_memory_limit: True
    php_version: "8.1"
    # TODO: fix consensus.php so this isn't necessary:
    php_default_version_debian: "8.1"
    mysql_root_password: {{ mysql_root_password }}

    ### This role
    aegir_db_password: "{{ mysql_root_password }}"
    aegir_frontend_url: "example.com" # change as desired
    aegir_http_service_type: nginx
    aegir_install_method: git
    aegir_skynet_enable: True
    aegir_admin_email: "do-not-reply@example.com"
    aegir_fix_ownership: True
    aegir_fix_permissions: True
    aegir_generate_makefile: True

    # Use BOA drush 8:
    aegir_drush_install_method: git
    aegir_drush_source_repo: 'https://github.com/omega8cc/drush'
    aegir_drush_source_install_version: '8-boa-micro'
    aegir_drush_source_update: True

    # Use Consensus' fork of Provision, with D10 support files patched in from BOA, and fixed:
    aegir_provision_repo: https://gitlab.com/consensus.enterprises/aegir/provision
    aegir_provision_version: 'd10-install-script-correct-config-var'
    aegir_provision_update: True

  roles:
    - role: consensus.mysql
      become: True
    - role: consensus.nginx
      become: True
    - role: consensus.php-versions
      become: True
    - role: consensus.php
      become: True
    - role: geerlingguy.composer
      become: True
    - role: consensus.aegir
      become: True

  tasks:

  - name: Check that Aegir front-end is installed and generate login link.
    shell: "drush @hm status && drush @hm uli"
    changed_when: False
    become: True
    become_user: "aegir"
    register: uli

  - debug: msg="{{ uli.stdout_lines }}"
