---
- name: "Set up roles for Aegir server configuration via Ansible."
  hosts: all

  tasks:

  - name: Ensure roles dir exists.
    file:
      path: roles
      state: directory

  - name: Ensure Aegir role is checked out.
    git:
      repo: https://gitlab.com/consensus.enterprises/ansible-roles/ansible-role-aegir
      dest: "roles/consensus.aegir"
      version: 8-meta-unfork-dependent-roles-where-possible
