---
roles:
  # Install from Ansible Galaxy.
  - name: geerlingguy.composer
  - name: geerlingguy.mysql
  - name: geerlingguy.nginx
  - name: geerlingguy.php
  - name: geerlingguy.php-versions

collections:
  - name: ansible.posix
  - name: community.general
  - name: community.mysql
  - name: consensus.aegir
    version: 1.0.1

