---
- name: "Aegir minion server install."
  hosts: all

  # Supply values for mysql_root_password and aegir_ssh_pub_key.

  vars:
    mysql_root_password: "{{ mysql_root_password }}"
    mysql_root_password_update: True
    nginx_manage_config: False
    nginx_remove_default_vhost: True
    php_cli_memory_limit: "2048M"
    php_enable_php_fpm: True
    php_enable_webserver: False
    php_set_cli_memory_limit: True
    php_version: "8.1"
    aegir_db_service_type: mysql
    aegir_db_pass: "{{ mysql_root_password }}"
    aegir_http_service_type: nginx
    aegir_ssh_pub_key: "{{ aegir_ssh_pub_key }}"

  roles:
    - role: consensus.php-versions
      become: yes
    - role: consensus.aegir-minion
      become: yes
